### ISSUE TITLE
Mobile / Tablet / Desktop / Fridge / whatever support

### ISSUE THREAD

**Issue by hans2103** [ericmann/Redis-Object-Cache#20]
Thank you for your great work... but how can I change the code to add a platform specific prefix?
On our website there are some differences between mobile and desktop output of HTML. (for example... not loading gigantic background image on mobile)
added 'fridge' for fun. ;-)
Not all differences can be solved with css.

**Comment by ethitter** [comment]
@hans2103, your page caching plugin, or custom code, should account for user agents, not the object cache. Most page caches provide support for this by varying the cache keys, so the object cache shouldn't also handle user-agent-specific variants.
