### ISSUE TITLE
Deprecate in lieu of https://github.com/tillkruss/redis-cache?

### ISSUE THREAD

**Issue by allella** [ericmann/Redis-Object-Cache#22]
Does it make sense to update the README to direct Wordpress users to Till Kruss' fork?

https://github.com/tillkruss/redis-cache
https://wordpress.org/plugins/redis-cache/

**Comment by ericmann** [comment]
A fork is a fork, not a replacement. Someone else forked the project. Great! That doesn't mean this is irrelevant or should be closed down/deprecated.

**Comment by allella** [comment]
True, but when people visit a project that hasn't been updated in two years and the person who forked the project is submitting pull requests back to the original it's unclear if one has replaced the other or if they are still both viable.

Appreciate your work.  However, keep in mind that you know the difference, whereas most random people like myself do not.

A note in the README explaining that both this project and Kruss' plugin are still active and viable would be handy.  I'd submit a pull request with an updated README but seems like the sort of thing you'd do, or not do.

Thanks again for your work.

Jim

**Comment by ericmann** [comment]
This is not the first fork and won't be the last. It's not my responsibility to maintain a list of all of the projects that have built upon my work.

To date, I know of at least 5 (not including tillkruss') projects in the wild that forked from this project.

**Comment by allella** [comment]
Again, appreciate your work. I've worked a lot more with Drupal over the years and it's typically much easier to find the active modules / plugins and modules often point to newer, better versions when code runs its course.  Hopefully the info below will help the next guy.

This project from [ericmann](https://github.com/ericmann/Redis-Object-Cache) and friends
--|[tillkruss](https://github.com/tillkruss/redis-cache) (a.k.a. [redis-cache](https://wordpress.org/plugins/redis-cache/)) - last commit Nov 2016
--|[shtrihstr](https://github.com/shtrihstr/redis-object-cache) - forked for reason unknown, presumed dead, last commit Oct 2015
--|[alleyinteractive](https://github.com/alleyinteractive/wp-redis) - last commit May 2014, presumed replaced by Pantheon Fork
-----|[pantheon-systems fork](https://github.com/pantheon-systems/wp-redis) (a.k.a. [wp-redis](https://wordpress.org/plugins/wp-redis/)) - last commit Nov 2016
-----|[tlovett1](https://github.com/tlovett1/redis-object-cache) - ensure compatibility with Batcache, last commit May 2016
-----|[WebDevStudios](https://github.com/WebDevStudios/wp-redis) - last commit May 2014, presumed deferral to Pantheon's fork
