### ISSUE TITLE
Meta fields wont update

### ISSUE THREAD

**Issue by timcv** [ericmann/Redis-Object-Cache#24]
Hi,

Im testing your plugin and I have some problems with meta values.
Im using ACF to create metaboxes.

The problem;
When Im changing text in metaboxes the new values won't show on the web page.

Do you have any suggestions on how to get this working?

**Comment by ghost** [comment]
@timsamuelsson have you seen this doc: https://www.jimwestergren.com/wordpress-with-redis-as-a-frontend-cache/? I ask because it links to [Predis](https://github.com/nrk/predis/) which looks very interesting.

**Comment by timcv** [comment]
Hi,

The solution you are linking is a fullpage cache solution. Im using nginx for that.

I need a redis solution for WPs object cache...

**Comment by ghost** [comment]
I like this Object Cache because it's simple and scales well from my read-only load testing. But coming from the world of static websites I've struggled to wrap my head around the differences between some of the various Redis caching solutions. So I appreciate your input, Tim. Could you point me in a direction for gaining greater control over caching of static assets served through Nginx without consideration of CDN?

**Comment by timcv** [comment]
No problems!

I use this plugin to purging the cache when i make changes to a post:
https://wordpress.org/plugins/nginx-helper/

On the plugin page above you can find several tutorials on how to set up Nginx with caching!
The big win with this solution is that you bypass PHP completely.

**Comment by ghost** [comment]
Thanks for sharing! I will pour over it soon. 🙏🏼

**Comment by ericmann** [comment]
@timsamuelsson I haven't explicitly tested with ACF. Are you sure this is a problem with the cache, or could it be a problem with ACF against _any_ cache? (I'd be curious if this was still present if using Memcached instead, as this extension is heavily derived from the stock MC alternatives.)

If you're still facing this problem, and are sure it's an issue with the Redis cache and not some weirdness with an integration, we can reopen. Closing for now, though, as this isn't something anyone else has reported and, without further details, isn't something I could fix anyway.

**Comment by ghost** [comment]
@ericmann I forgot to follow-up. I used this sucker on a WordPress site and slammed it with with a load tester. Here're the results of 10000 VU load with this exact object cache when applied to minimal use case: https://hackernoon.com/putting-wordpress-into-hyperdrive-4705450dffc2

I've got tons of raw data sitting in New Relic and from WPT if you want exports.
